-- Creating the customer_information table
CREATE TABLE customer_information (
    customer_id VARCHAR2(36) PRIMARY KEY,
    account_number VARCHAR2(20) UNIQUE,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    middle_name VARCHAR2(50),
    email VARCHAR2(100),
    phone_number VARCHAR2(20),
    mobile_number VARCHAR2(20),
    address_line1 VARCHAR2(100),
    address_line2 VARCHAR2(100),
    city VARCHAR2(50),
    state VARCHAR2(50),
    postal_code VARCHAR2(20),
    country VARCHAR2(50),
    date_of_birth DATE,
    ssn VARCHAR2(20),
    nationality VARCHAR2(50),
    occupation VARCHAR2(50),
    employer_name VARCHAR2(100),
    employer_phone VARCHAR2(20),
    annual_income NUMBER(15,2),
    net_worth NUMBER(15,2),
    credit_score NUMBER(3),
    account_type VARCHAR2(20),
    account_status VARCHAR2(20),
    account_open_date DATE,
    account_close_date DATE,
    portfolio_id VARCHAR2(36),
    broker_id VARCHAR2(36),
    branch_code VARCHAR2(10),
    region VARCHAR2(50),
    customer_segment VARCHAR2(20),
    risk_tolerance VARCHAR2(20),
    investment_objective VARCHAR2(50),
    investment_experience VARCHAR2(20),
    income_source VARCHAR2(50),
    tax_id VARCHAR2(20),
    tax_residency VARCHAR2(50),
    kyc_status VARCHAR2(20),
    aml_flag VARCHAR2(10),
    compliance_status VARCHAR2(20),
    account_balance NUMBER(15,2),
    margin_balance NUMBER(15,2),
    available_cash NUMBER(15,2),
    last_transaction_date DATE,
    last_login_date TIMESTAMP,
    preferred_currency VARCHAR2(3),
    communication_preference VARCHAR2(20),
    language_preference VARCHAR2(20),
    time_zone VARCHAR2(50),
    customer_rating VARCHAR2(10),
    referral_source VARCHAR2(50),
    marketing_consent VARCHAR2(10),
    account_manager VARCHAR2(100),
    account_manager_id VARCHAR2(36),
    last_review_date DATE,
    next_review_date DATE,
    customer_notes VARCHAR2(200),
    created_by VARCHAR2(50),
    created_date DATE,
    updated_by VARCHAR2(50),
    updated_date DATE,
    client_type VARCHAR2(20),
    investment_horizon VARCHAR2(20),
    preferred_contact_method VARCHAR2(20),
    alternate_email VARCHAR2(100),
    emergency_contact_name VARCHAR2(100),
    emergency_contact_phone VARCHAR2(20),
    relationship_manager VARCHAR2(100),
    risk_score NUMBER(3),
    compliance_notes VARCHAR2(200),
    batch_id VARCHAR2(36)
);

-- Creating indexes for frequently queried columns
CREATE INDEX idx_customer_email ON customer_information(email);
CREATE INDEX idx_customer_ssn ON customer_information(ssn);
CREATE INDEX idx_customer_account_number ON customer_information(account_number);
CREATE INDEX idx_customer_portfolio_id ON customer_information(portfolio_id);
CREATE INDEX idx_customer_broker_id ON customer_information(broker_id);
